(defproject spaces-search-api "0.1.0-SNAPSHOT"
  :description "FIXME: write description"
  :url "http://example.com/FIXME"
  :dependencies [[ring "1.3.2"]
                 [environ "1.0.0"]
                 [clj-http "1.1.1"]
                 [clj-time "0.9.0"]
                 [http-kit "2.1.19"]
                 [compojure "1.3.3"]
                 [liberator "0.12.2"]
                 [rubberlike "0.2.0"]
                 [reloaded.repl "0.1.0"]
                 [im.chit/ribol "0.4.0"]
                 [prismatic/schema "0.4.1"]
                 [prismatic/plumbing "0.4.2"]
                 [org.clojure/clojure "1.6.0"]
                 [im.chit/hara.common "2.1.11"] 
                 [com.taoensso/timbre "3.4.0"]
                 [org.immutant/messaging "2.1.0"]
                 [clojurewerkz/elastisch "2.1.0"]  
                 [com.stuartsierra/component "0.2.3"] 
                 [com.cognitect/transit-clj "0.8.271"]
                 [io.clojure/liberator-transit "0.3.0"]
                 [org.hornetq/hornetq-jms-server "2.3.17.Final"]
                 [org.clojure/core.async "0.1.346.0-17112a-alpha"] 
                 [ring-transit "0.1.3" :exclusions [prismatic/plumbing]]]
  :profiles {:dev {:source-paths ["dev"]
                   :dependencies [[org.clojure/tools.namespace "0.2.8"]
                                  [org.clojure/java.classpath "0.2.2"]
                                  [ring-mock "0.1.5"]   
                                  [javax.servlet/servlet-api "2.5"]]}
             :uberjar {:main ^:skip-aot spaces-search-api.system}})
